apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation
spec:
  selector:
    matchLabels:
      app: recommendation
  template:
    metadata:
      labels:
        app: recommendation
    spec:
      containers:
      - name: rec
        image: hands-on/recommendation-service:v1
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "docker,prod"
        resources:
          requests:
            memory: "200Mi"
          limits:
            memory: "400Mi"
